# GitHub Actions workflow for running Cypress end-to-end tests
name: Cypress Tests

# Trigger conditions: run this workflow when code is pushed or PRs are opened
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Cypress
    runs-on: ubuntu-latest # Use Ubuntu Linux runner for the tests

    steps:
      # Step 1: Get the source code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Use official Cypress GitHub Action (handles Node.js, npm install, Cypress install & run)
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # Record to Cypress Dashboard (optional - remove if you don't want dashboard integration)
          record: true
        env:
          # Cypress Dashboard record key - add your key to GitHub repository secrets
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      # Step 3: Upload test artifacts (screenshots, videos) if tests fail
      - name: Upload Cypress artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
          if-no-files-found: ignore




